url: "https://www.gospeldesk.org"
sass:
  sass_dir: .
exclude: ["CNAME", "Makefile", "README.md", "Gemfile", "Gemfile.lock", "prep-email.py"]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      html_title_sep: "-"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
collections:
  posts:
    permalink: "/:year/:title/"
