url: https://www.gospel-desk.com
sass:
  sass_dir: .
exclude: ["bin"]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      html_title_sep: "-"
      suppress_subscribe: "yes"
collections:
  posts:
    permalink: /updates/:year/:title/
