url: https://www.gospeldesk.org
sass:
  sass_dir: .
exclude: ["CNAME", "Makefile", "README.md"]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      html_title_sep: "-"
      show_follow_along: "yes"
collections:
  posts:
    permalink: /blog/:year/:title/
