url: "https://www.gospeldesk.org"
sass:
  sass_dir: .
exclude:
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "README.md"
  - "bin"
  - "prep-email.py"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      html_title_sep: "-"
      clip_bottom: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      clip_bottom: false
collections:
  posts:
    permalink: "/:year/:title/"
